# server API configuration
version: 'v1'
port: 80

# docker registry configurations
docker:
  registry:
    url: 'mica-registry'
    port: 5000

# configuration of the time series databases
database:
  default:
    url: 'localhost'
    port: 9000
  influx:
    url: 'localhost'
    port: 8086
    user: 'root' # Default user for influx
    password: 'root' # Default user for influx
    tablename: 'mica-framework'

# configuration of the redisDB for server-caching
redisDB:
  hostname: 'localhost'
  port: 6379
  keys:
    victims:
      name: 'victim'
    attacks:
      name: 'attacks'