# server API configuration
version: 'v1'
port: 80

# docker registry configurations
docker:
  registry:
    url: 'mica-registry'
    port: 5000

# configuration of the time series databases
database:
  default:
    url: 'localhost'
    port: 9000
  influx:
    url: '192.168.123.223'
    port: 8086
    user: '' #FIXME that's again something what sould be a secret!!
    password: '' # FIXME that's again something what should be a secret!!
    tablename: 'mica-framework'

# configuration of the redisDB for server-caching
redisDB:
  hostname: 'localhost'
  port: 6379
  keys:
    victims:
      name: 'victim'
    attacks:
      name: 'attacks'